### ISSUE TITLE
Research Pros and Cons of using Javascript Technologies in Project 

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#1]
One of the requirements of this project "So far as possible, site functionality should not rely on javascript or CSS". From a development standpoint this can be limiting since web development is moving more towards the client side. 

We would like to do research into the pros and cons of relying on Javascript so we can dispute the validity of this requirement

**Comment by maeutic** [comment]
As mentioned in the email, this requirement was poorly phrased: javascript and CSS should be implemented in ways which do not impeded accessibility. Many common implementations impede or prevent those with disabilities from easily reading and/or interacting with sites. Our goal is to prevent such issues.

Resources mentioned in the email which will be helpful to review include:

https://www.w3.org/WAI/standards-guidelines/wcag/
https://www.w3.org/TR/WCAG20/#conformance
https://a11yproject.com/resources
https://a11yproject.com/checklist
https://webaim.org/techniques/javascript/
https://webaim.org/resources/designers/
http://wave.webaim.org/
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility
https://alistapart.com/article/accessibility-whack-a-mole

**Comment by vinaygopinath** [comment]
As discussed on Jun 30, we've agreed to use Javascript in the frontend site and not go out of our way to support users who've disabled JS. We intend to use a combination of server-side rendering and avoiding certain UI patterns (modals, dynamic navigation) to minimise accessibility issues.

Marking this issue as closed / N/A
