### ISSUE TITLE
Present Possible Technology Stacks to Use

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#10]
1. We need to confirm with Amelia and Mac if we want to support users that have JS turned of. The ability to use certain JS technologies impacts the design of the application

2. Vinay and Stephanie would like to use React for the Client side but Amelia has reservations about this since this technology is not battle tested. What other options are available? 
       a. Vinay believes that we can render all the JS on the server and then serve it to the client. This 
           would allow browsers with JS and CSS turned off to function as intended thus not impacting 
           user experience. 

3.  Server side language options: 
     a. Node.js
     b. Go
     c. Python 
     d. PHP

4. Database options: 
    a. Relational Database (we believe this is best since the data is very structured) 
         I. MySQL
         II. Postgres
    b. Non-Relational Database
        I. Mongodb

**Comment by Revencher** [comment]
My again my primary concern is liability and simplicity.
That being said if you feel you are working too far out of your realm of knowledge then go with what you know.

I think the best guidance on this snow is going to come from Mac

**Comment by shonore** [comment]
Amelia said that she does not want JS and CSS to impair developers from following WCAG. We want the application to function as intended in places with poor cell reception and internet connection (e.g. Third world countries). Geoff is okay with devs using technologies they are comfortable with as long as it supports differently abled users

**Comment by shonore** [comment]
Amelia has another team member who is going to join the project. We are all okay with this. Amelia and Geoff are okay with using React for front end. We want to allow more devs to contribute to the project, but we would like to lay down the project foundation first to avoid mayhem

**Comment by shonore** [comment]
For the server side code we believe that Node.JS or Python would be the best options. Go may not be good for this project since it is open source and we want others to contribute to it in the future and PHP is not ideal either

**Comment by shonore** [comment]
We can also explore ember.js as well since Mac is familiar with this

**Comment by shonore** [comment]
We are going to use a relational database. We are okay with either Postgres or MySQL. Vinay has prior experience with Postgres. We need to get Mac's feedback along with Josh's feedback (we have not connected with him yet). Vinay will follow up with Mac and Josh regarding this
