### ISSUE TITLE
Research and discuss sharing options

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#13]
Research scope of options for sharing an event. Who can you share with? Only other users in the platform or anyone? How can you share (e.g url, text message, email , facebook, etc)

**Comment by maeutic** [comment]
As always, the final word on this is Geoff's. My inclination for the alpha would be to get the basic functions of the site as solid as possible, with sharing to external resources as a "nice to have" rather than a requirement. I'll touch base with Geoff & see what he has to say.
