### ISSUE TITLE
Create RESTful API for Syna3C Project 

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#16]
Create REST API with the following technologies: 
-Node.js
-Typescript
-Express
-Postgres 

Must have CRUD operations for each table in the TDD:(https://docs.google.com/spreadsheets/d/1dToVZmI7mneLFa3jK71aajSj83xV4MAHNn9DXzavEDk/edit?usp=sharing)

**Comment by vinaygopinath** [comment]
The basic framework for the REST api has been set up with the technologies listed above. Closing this issue in favour of more modular issues, to be created in the backend repo.
