### ISSUE TITLE
Create Low Fidelity Wireframe of Application 

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#2]
We need a low fidelity mockup to visualize the following features: 
-Signup
-Sign-In
-Admin Dashboard 
-Profile Page
-Create Event
-Create Sub-Event
-Create Coordination Posts
-View Event/Sub-Event Feed
-View Event/Sub-Event Details 
-View Coordination Posts
-Commenting 
-Contact Us Form

**Comment by Revencher** [comment]
I don't understand what you are asking for?

**Comment by maeutic** [comment]
Geoff, a wireframe mockup is basically a very bare-bones visualization of parts of a web interface. Think rough line sketches of parts of a house.
