### ISSUE TITLE
Setup Postgres Database and tables

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#24]

**Comment by shonore** [comment]
I set up the User table... still need to do the other tables

**Comment by shonore** [comment]
Created the Permissions and Users table. Still need to create the other tables in the TDD

**Comment by vinaygopinath** [comment]
Users, Events and ~Permissions~ Roles tables have been created so far.
Closing this issue in favour of creating additional tables as necessary while working on issues in the backend repo.
