### ISSUE TITLE
Research Cloud Platforms - Azure vs. AWS vs. GCP vs. Heroku vs. others

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#3]
We want to explore the best options for hosting the applications.

**Comment by Revencher** [comment]
By all means.

**Comment by shonore** [comment]
Mac already as a AWS server configured and we would like to use this as the dev server. If Mac is okay with configuring another hosting platform (e.g. Azure) we can use that for production if it provides better rates

**Comment by shonore** [comment]
Action Item: Vinay is going to reach out to Mac to get his feedback on this idea

**Comment by shonore** [comment]
Vinay reached out to Mac and has not heard back from Mac yet. Amelia said that we currently do have a nonprofit available to request for credit through TechSoup for Azure

**Comment by shonore** [comment]
We are going to use a managed route for cloud platforms

**Comment by shonore** [comment]
Amelia we are waiting for the EIN (tax id #) to be filed for the non-profit. Once that is complete we can reach out to TechSoup for Azure credit

**Comment by maeutic** [comment]
@shonore, TechSoup requires full 501(c)(3) status to be eligible to register. That will take ~3mos after filing the 1023-EZ. The EIN is needed for other reasons. As mentioned on the phone, there is an extant nonprofit "umbrella-ing" this project, and we can get Azure services through their account until Syna3C's nonproft status is codified with the IRS.
