### ISSUE TITLE
Adding field level validation to Login/Sign Up UI

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#30]
**Add front end validation:**
**Field level validations**
**Add user friendly messages for error scenarios:** 
**Invalid login credentials:**
No email/username/password does not match
Server unavailable
Client unavailable
Using swagger to add login functionality
Character limits for fields

**Comment by vinaygopinath** [comment]
Closed in https://github.com/Syna3C/frontend/pull/3
