### ISSUE TITLE
Confirm with Amelia and Mac on using Progressive Web App Framework

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#4]
We believe that using a Progressive Web App is the best approach to meet the requirements of the project. We wanted to confirm with the rest of the team if they were on board with this.

**Comment by Revencher** [comment]
I am out of my league here. But my cat mean concern for anything you do is simplicity and reliability.

**Comment by shonore** [comment]
Example of this can be found here: https://pwa.rocks/

Basically, this a way for us to have a mobile first web app and website without having a separate code base for the mobile and web version of the application. The user can choose if they want to use the PWA or view the website normally in the browser. This is offline first so it will be ideal for supporting users who have poor internet connection or poor cell reception

**Comment by shonore** [comment]
Geoff and Amelia are okay with this.

**Comment by shonore** [comment]
Geoff mentioned that he would like to implement repeater technology (?) so offline cell phones can bounce signals off other cell phones in a nearby vicinity

Amelia shared the following for supporting users in densely crowed areas
 http://www.servalproject.org/
