### ISSUE TITLE
Backend - GET all Events

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#41]
1. A SQL query is generated for getting all the Events - Pull n records at a time, where n is a request parameter
2. The SQL query is put in a .sql file in the docs/ directory
3. Create function in  EventRouter.ts file that calls the GET All Events SQL query

**Comment by shonore** [comment]
Vinay completed completed this

**Comment by vinaygopinath** [comment]
Closed in https://github.com/Syna3C/backend/pull/5
