### ISSUE TITLE
Setting Up Postgres Database on Microsoft Azure

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#46]
-We have $5000 of credit to use. 
-We need to set up hosting for the Syna3C application.
-Server Stack Options: 
-Postgre
-Linux Stack

**Comment by maeutic** [comment]
Amelia & Mac are set up as General Administrators.
Stephanie & Vinay are Application Administrators.
Geoff is set up as a standard User.

Waiting on CCS treasurer to add cc info to Azure account before we can begin subscribing to services.

**Comment by shonore** [comment]
Since we are using the managed route we will not have to set up a server stack. We are just going to subscribe to use the SQL Database and App Services already configured in Azure
