### ISSUE TITLE
Frontend - Service call to GET Events

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#53]
Write code to call the GET Events API

**Comment by shonore** [comment]
**UI Field           |   Table Column**
Event Name   |    Events.Event Name
Description    |    Events.Event Description
Organizer(s)  |    User.username
Location         |    Event.Address, Event.Address2, Event.City, Event.State, Event.Zip (will be a json)
Created x time ago  | Events.createOn (use moments.js library)

**Comment by vinaygopinath** [comment]
Recreated with more detail here: https://github.com/Syna3C/frontend/issues/7
