### ISSUE TITLE
Frontend - GET Coordination Post and Subevent Count **

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#55]
For each event card in the UI, the number of coordination posts should be displayed. In addition, the number of subevents should be displayed. These will be displayed via tooltips when user interacts with icons in the bottom right of the event card(icons TBA).

**Comment by vinaygopinath** [comment]
Closing in favour of the more detailed: https://github.com/Syna3C/frontend/issues/8
