### ISSUE TITLE
Frontend - Update root page and add logic for displaying side panel 

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#57]
Description: 
As a user, I should be able to view the Syna3C event feed when first enter the website so that I can instantly get access to the information about a disaster relief event

Acceptance Criteria: 
1. When a user first enters the Syna3C website they should land on a page that displays the event feed data. 
2. Users should only be able to view the events. They are permitted to click to view the event details. 
3. The left-side panel should not be visible to the user if they have not logged in
4. Once the user has logged in, the left-side panel should be visible on the events page

**Comment by vinaygopinath** [comment]
Fixed in https://github.com/Syna3C/frontend/pull/6
