### ISSUE TITLE
Come up with use cases for User Check-In Feature

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#6]
We need to come up with some use cases for the Check-In feature. We believe that this feature is important and we would like to include it in the first release.

**Comment by Revencher** [comment]
Ok. Just make sure you weren't putting too much on your plate.

**Comment by shonore** [comment]
We spoke with Amelia and Geoff and they gave the following: 

Use Case # 1: 2 Users are going to carpool to an event. When the users met they take pictures of the other person and their license plate and then upload it to the website. We would also capture their location. This is for ensuring the safety of the users. Images would only store images for x amount of time. The length of time that the image is allowed to stay on the site is determined by Admin and organizer.

Use Case # 2: A user in a disaster zone can take a photo of a blocked road and then upload it to the website along with the geo-location of where the photo was taken. Images would only store images for x amount of time. The length of time that the image is allowed to stay on the site is determined by Admin and organizer.

**Comment by shonore** [comment]
Once the event is closed or has expired all of the check-ins will have to be cleared out

**Comment by shonore** [comment]
For the alpha lets just have a simple check-in feature. We would like to just to have the following functionalities in the this feature: 
1. Take a person photo
2. Take a license plate photo
3. Location photo
4. Other photo
4. Share Geolocation
5. Comment section 

This feature is optional for the user participating into an event. The check-in would only be viewable to admins ,organizers of events, and, originating users
