### ISSUE TITLE
Get specifics for coordination post creation 

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#7]
Stakeholders (Amelia/Geoff) needs to come up the following information for Coordination post creation: 
1.  Finite list of what the categories are and their conditional logic for coordination post form
2. For Coordination Post creation do we just need to know for who the resource is for [name of community or city or region] or do we need more specific information?

**Comment by maeutic** [comment]
I'll work on this as I can this week.

**Comment by Revencher** [comment]
I didn't quite understand the first question.

Answer to the second question is we will need to know where the supplies are located and where they need to go.

**Comment by maeutic** [comment]
Here's the scope statement.
[Syna3C Logistics Coordination Platform Scope Statement.docx](https://github.com/Syna3C/Syna3C-Project/files/2152001/Syna3C.Logistics.Coordination.Platform.Scope.Statement.docx)

**Comment by shonore** [comment]
See coordination post section in Scope document for the exhaustive list of fields for coordination post creation form

**Comment by shonore** [comment]
We would like to refer to the Coordination posts as Coordination Threads and the responses on the coordination threads would be referred to as the coordination post
