### ISSUE TITLE
Discuss Messaging System Options

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#8]
We need to discuss the importance of the instant chat/direct email message feature with Amelia. Vinay and Stephanie believe that it would take just as much effort to implement a Reddit like email message system as instant chat

**Comment by Revencher** [comment]
That sounds fine. But let's remember to keep it symbol for Alpha.

**Comment by shonore** [comment]
We need to research if there is an existing open source project we can implement in place of building an messaging system.

**Comment by maeutic** [comment]
Let's take a look at https://github.com/AppLozic/React-JS-Chat

**Comment by shonore** [comment]
We would like to include it into the alpha but this ranks lower in priority than other features so we cannot guarantee that this will fit into the alpha release

**Comment by shonore** [comment]
Vinay and Stephanie are going to research this still

**Comment by shonore** [comment]
Vinay researched this and found that what is available in Github are Client side components for messaging/chat. Vinay found some full functional chat application we could integrate but they are proprietary software so we would have to subscribe to them. Amelia is going to reach out to Josh Morris for consultation regarding this issue.

**Comment by shonore** [comment]
Amelia reached out to Josh, however he has not responded back yet. Amelia is requesting Vinay to give better description of issue so she can communicate it to Josh

**Comment by maeutic** [comment]
https://github.com/totaljs/messenger

https://github.com/martynsmith/node-irc

**Comment by maeutic** [comment]
RabbitMQ info:

https://www.rabbitmq.com/#features
https://www.rabbitmq.com/download.html
https://www.rabbitmq.com/devtools.html

**Comment by shonore** [comment]
We think that this is something that can be tackled in a code-a-thon. Geoffrey is working with Dr. Tanis at UTC to possible get this to happen.
