### ISSUE TITLE
Research and Present information on NPL

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#9]
Natural Language Processing (NLP) - We need to present what NLP is to Amelia and other stakeholders. In addition, we should discuss the costs, risks, development time, and, production support efforts of using this technology.

**Comment by Revencher** [comment]
I Googled it real quick. I can see how it would be useful but wonder if it's necessary or prudent for the alpha?

**Comment by maeutic** [comment]
Let's take a look at these:

https://opennlp.apache.org/
https://spacy.io/
https://stanfordnlp.github.io/CoreNLP/
http://www.nltk.org/
https://gate.ac.uk/

**Comment by shonore** [comment]
We are going to do more research on this. Amelia is going to find open source solutions for this. The purpose of implementing this technology is to reduce duplicate events/sub-events/posts from being created and to automatically generate tags based on the information entered when a post is created or edited. Tags may be used as a filter for searches.

**Comment by shonore** [comment]
The NPL is going to be implemented on the server so it does not have to be compatible with React. We will revisit this once we flesh out the website more
